export const blocklyBlocks = [
  { type: 'arduino_setup', message0: 'Setup %1 %2', args0: [{type:'input_dummy'},{type:'input_statement',name:'DO'}],
    colour: 210, tooltip: 'Выполняется один раз' },
  { type: 'arduino_loop', message0: 'Loop %1 %2', args0: [{type:'input_dummy'},{type:'input_statement',name:'DO'}],
    colour: 210, tooltip: 'Постоянный цикл' },
  { type: 'digital_write', message0: 'записать на пин %1 значение %2',
    args0: [{type:'field_number',name:'PIN',value:13,min:0,max:13},
            {type:'input_value',name:'VALUE'}],
    previousStatement: null, nextStatement: null, colour: 120 },
  { type: 'digital_read', message0: 'читать пин %1',
    args0: [{type:'field_number',name:'PIN',value:2,min:0,max:13}],
    output: 'Number', colour: 120 },
  { type: 'analog_write', message0: 'PWM пин %1 значение %2',
    args0: [{type:'field_number',name:'PIN',value:9,min:0,max:13},
            {type:'input_value',name:'VALUE'}],
    previousStatement: null, nextStatement: null, colour: 60 },
  { type: 'analog_read', message0: 'аналог. пин %1',
    args0: [{type:'field_dropdown',name:'PIN',
      options:[['A0',0],['A1',1],['A2',2],['A3',3],['A4',4],['A5',5]]}],
    output: 'Number', colour: 60 },
  { type: 'delay_ms', message0: 'ждать %1 мс',
    args0: [{type:'field_number',name:'MS',value:1000,min:0}],
    previousStatement: null, nextStatement: null, colour: 30 },
  { type: 'pin_mode', message0: 'пин %1 режим %2',
    args0: [{type:'field_number',name:'PIN',value:13},
            {type:'field_dropdown',name:'MODE',
              options:[['OUTPUT','OUTPUT'],['INPUT','INPUT'],['INPUT_PULLUP','INPUT_PULLUP']]}],
    previousStatement: null, nextStatement: null, colour: 120 }
];